export const ADVERTISEMENTS_GET_REQUEST = 'ADVERTISEMENTS_GET_REQUEST';
export const ADVERTISEMENTS_GET_SUCCESS = 'ADVERTISEMENTS_GET_SUCCESS';
export const ADVERTISEMENTS_GET_FAIL = 'ADVERTISEMENTS_GET_FAIL';
