export const BLOGS_GET_REQUEST = 'BLOGS_GET_REQUEST'
export const BLOGS_GET_SUCCESS = 'BLOGS_GET_SUCCESS'
export const BLOGS_GET_FAIL = 'BLOGS_GET_FAIL'

export const BLOGS_DETAILS_GET_REQUEST = 'BLOGS_DETAILS_GET_REQUEST'
export const BLOGS_DETAILS_GET_SUCCESS = 'BLOGS_DETAILS_GET_SUCCESS'
export const BLOGS_DETAILS_GET_FAIL = 'BLOGS_DETAILS_GET_FAIL'