export const LOGIN_GET_REQUEST = 'LOGIN_GET_REQUEST';
export const LOGIN_GET_SUCCESS = 'LOGIN_GET_SUCCESS';
export const LOGIN_GET_FAIL = 'LOGIN_GET_FAIL';

export const SIGNUP_GET_REQUEST = 'SIGNUP_GET_REQUEST';
export const SIGNUP_GET_SUCCESS = 'SIGNUP_GET_SUCCESS';
export const SIGNUP_GET_FAIL = 'SIGNUP_GET_FAIL';

export const OTP_GET_REQUEST = 'OTP_GET_REQUEST';
export const OTP_GET_SUCCESS = 'OTP_GET_SUCCESS';
export const OTP_GET_FAIL = 'OTP_GET_FAIL';

export const OTPRESEND_GET_REQUEST = 'OTPRESEND_GET_REQUEST';
export const OTPRESEND_GET_SUCCESS = 'OTPRESEND_GET_SUCCESS';
export const OTPRESEND_GET_FAIL = 'OTPRESEND_GET_FAIL';
