export const LOGIN_GET_REQUEST = 'LOGIN_GET_REQUEST'
export const LOGIN_GET_SUCCESS = 'LOGIN_GET_SUCCESS'
export const LOGIN_GET_FAIL = 'LOGIN_GET_FAIL'



export const SIGNUP_GET_REQUEST = 'SIGNUP_GET_REQUEST'
export const SIGNUP_GET_SUCCESS = 'SIGNUP_GET_SUCCESS'
export const SIGNUP_GET_FAIL = 'SIGNUP_GET_FAIL'



