export const MENTOR_LIST_REQUEST = 'MENTOR_LIST_REQUEST'
export const MENTOR_LIST_SUCCESS = 'MENTOR_LIST_SUCCESS'
export const MENTOR_LIST_FAIL = 'MENTOR_LIST_FAIL'
export const MENTOR_LIST_SEARCH = 'MENTOR_LIST_SEARCH'


export const MENTOR_LIST_DETAILS_REQUEST = 'MENTOR_LIST_DETAILS_REQUEST'
export const MENTOR_LIST_DETAILS_SUCCESS = 'MENTOR_LIST_DETAILS_SUCCESS'
export const MENTOR_LIST_DETAILS_FAIL = 'MENTOR_LIST_DETAILS_FAIL'
