export const PACKAGES_GET_REQUEST = 'PACKAGES_GET_REQUEST';
export const PACKAGES_GET_SUCCESS = 'PACKAGES_GET_SUCCESS';
export const PACKAGES_GET_FAIL = 'PACKAGES_GET_FAIL';
export const PACKAGES_GET_SEARCH = 'PACKAGES_GET_SEARCH';
