export const PROGRAM_GET_REQUEST = 'PROGRAM_GET_REQUEST';
export const PROGRAM_GET_SUCCESS = 'PROGRAM_GET_SUCCESS';
export const PROGRAM_GET_FAIL = 'PROGRAM_GET_FAIL';
export const PROGRAM_GET_SEARCH = 'PROGRAM_LIST_SEARCH';
