export const SUBSCRIBE_STUDENT_REQUEST = 'SUBSCRIBE_STUDENT_REQUEST';
export const SUBSCRIBE_STUDENT_SUCCESS = 'SUBSCRIBE_STUDENT_SUCCESS';
export const SUBSCRIBE_STUDENT_FAIL = 'SUBSCRIBE_STUDENT_FAIL';

export const SUBSCRIBE_PROFESSIONAL_REQUEST = 'SUBSCRIBE_PROFESSIONAL_REQUEST';
export const SUBSCRIBE_PROFESSIONAL_SUCCESS = 'SUBSCRIBE_PROFESSIONAL_SUCCESS';
export const SUBSCRIBE_PROFESSIONAL_FAIL = 'SUBSCRIBE_PROFESSIONAL_FAIL';

export const SUBSCRIBE_ENTREPRENEUR_REQUEST = 'SUBSCRIBE_ENTREPRENEUR_REQUEST';
export const SUBSCRIBE_ENTREPRENEUR_SUCCESS = 'SUBSCRIBE_ENTREPRENEUR_SUCCESS';
export const SUBSCRIBE_ENTREPRENEUR_FAIL = 'SUBSCRIBE_ENTREPRENEUR_FAIL';
