export const WEBSITE_CONTENT_GET_REQUEST = 'WEBSITE_CONTENT_GET_REQUEST';
export const WEBSITE_CONTENT_GET_SUCCESS = 'WEBSITE_CONTENT_GET_SUCCESS';
export const WEBSITE_CONTENT_GET_FAIL = 'WEBSITE_CONTENT_GET_FAIL';
